on: [push]

jobs:
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Run SAST Analysis
        uses: soos-io/soos-sast-github-action@v1.0.1
        with:
          source_code_path: 'juice-shop'
          project_name: ${{ github.repository }}
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          
