on: [push]

jobs:
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SOOS SAST Analysis
        id: soos_sast
        uses: soos-io/soos-sast-github-action@v1
        with:
          project_name: ${{github.repository}}
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          log_level: 'debug'
          verbose: true

      - name: List workspace contents for debugging
        run: ls -R /github/workspace

      - name: Find and list SAST files
        run: |
          SAST_FILES=$(find /github/workspace -name '*.json')
          if [ -z "$SAST_FILES" ]; then
            echo "No SAST files found."
            exit 1
          fi
          echo "SAST files found:"
          echo "$SAST_FILES"
